#include <stdio.h>
#include<stdlib.h>
#include <conio.h>
#include <windows.h>
int i;

void BarraProgressao()
{
printf("\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB \xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB      \xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB \xDB\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB \n");
printf("\xDB\xDB   \xDB\xDB \xDB\xDB \xDB\xDB   \xDB\xDB \xDB\xDB      \xDB\xDB \xDB\xDB    \xDB\xDB    \xDB\xDB    \xDB\xDB      \xDB\xDB      \xDB\xDB   \xDB\xDB\n");
printf("\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB \xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB      \xDB\xDB \xDB\xDB    \xDB\xDB    \xDB\xDB    \xDB\xDB\xDB\xDB\xDB   \xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\n");
printf("\xDB\xDB   \xDB\xDB \xDB\xDB \xDB\xDB   \xDB\xDB \xDB\xDB      \xDB\xDB \xDB\xDB    \xDB\xDB    \xDB\xDB    \xDB\xDB      \xDB\xDB      \xDB\xDB   \xDB\xDB\n");
printf("\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB \xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB \xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB     \xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB \xDB\xDB   \xDB\xDB\n");                                                              
printf("\n");

printf("\xdb\xDF\xDF \xdb\xDF\xDF \xDF\xDF\xdb \xdb\xDF\xdb   \xdb\xDF\xDC \xdb\xDF\xDF \xdb\xDC\xdb   \xdb \xdb \xDF\xdb\xDF \xdb\xDF\xdb \xdb\xDF\xDC \xdb\xDF\xdb \xdb\n");
printf("\xDF\xDF\xdb \xdb\xDF\xDF   \xdb \xdb\xDF\xdb   \xdb\xDF\xDC \xdb\xDF\xDF \xdb \xdb   \xDF\xDC\xDF  \xdb  \xdb \xdb \xdb \xdb \xdb \xdb \xDF\n");
printf("\xDF\xDF\xDF \xDF\xDF\xDF \xDF\xDF  \xDF \xDF   \xDF\xDF  \xDF\xDF\xDF \xDF \xDF    \xDF  \xDF\xDF\xDF \xDF \xDF \xDF\xDF  \xDF\xDF\xDF \xDF\n");
printf("\n");
//printf("\x);


                                                                                                    
        printf("                  \xDB\xDB\xDB\xDB                                                                                      \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB                                                                                    \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB                                                                                    \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB                                                                                    \n");fflush(stdout);
        printf("                  \xDB\xDB                                                                                        \n");fflush(stdout);
        printf("                                                                                                            \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB              \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB            \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB                          \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB        \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB                      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB              \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB        \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB            \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB        \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB            \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB        \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB          \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB          \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB            \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB            \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB          \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB              \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB              \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB            \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB              \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB            \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB              \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB            \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB            \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB              \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB              \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB              \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB          \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB        \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB                \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB                \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB                  \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB                  \n");fflush(stdout);
        printf("                \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB          \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB        \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB                    \n");fflush(stdout);
                                                                                                                                                              
	
	printf("\n\n\n");	                                                            
    printf("            \xDB\xDB\xDB\xDB                                                  \n");fflush(stdout); 
    printf("          \xDB\xDB\xDB\xDB\xDB\xDB                                                  \n");fflush(stdout);
    printf("            \xDB\xDB                                                    \n");fflush(stdout);
    printf("          \xDB\xDB\xDB\xDB            \xDB\xDB                                \xDB\xDB\xDB\xDB  \n");fflush(stdout);
    printf("          \xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB            \xDB\xDB\xDB\xDB    \n");fflush(stdout);
    printf("          \xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB        \xDB\xDB\xDB\xDB\xDB\xDB    \n");fflush(stdout);
    printf("          \xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB      \n");fflush(stdout);
    printf("          \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB        \xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB        \xDB\xDB\xDB\xDB\xDB\xDB      \n");fflush(stdout);
    printf("          \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB        \xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB          \xDB\xDB\xDB\xDB\xDB\xDB      \n");fflush(stdout);
    printf("          \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB        \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB        \n");fflush(stdout);
    printf("          \xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB        \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB        \n");fflush(stdout);
    printf("          \xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB          \n");fflush(stdout);
    printf("          \xDB\xDB\xDB\xDB\xDB\xDB    \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB  \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB          \n");fflush(stdout);
    printf("            \xDB\xDB\xDB\xDB        \xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB\xDB\xDB\xDB\xDB      \xDB\xDB\xDB\xDB            \n");fflush(stdout);
	printf("\n\n\n");	
                                                                                                                                                                                                                                                
                                                                               
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                
                                                                                            
		
	printf("+===================================================================================================+\n");
	printf("|A   G   U   A   R    D    E       O         S  I   S  T   E   M   A      C  A  R  R  E  G   A   R !|\n");
	printf("+===================================================================================================+\n");
	printf("\n");
	printf("\n    A0   -        \xA0");
printf("\n    A1   -        \xA1");
printf("\n    A2   -        \xA2");
printf("\n    A3   -        \xA3");
printf("\n    A4   -        \xA4");
printf("\n    A5   -        \xA5");
printf("\n    A6   -        \xA6");
printf("\n    A7   -        \xA7");
printf("\n    A8   -        \xA8");
printf("\n    A9   -        \xA9");
printf("\n    AA   -        \xAA");
printf("\n    AB   -        \xAB");
printf("\n    AC   -        \xAC");
printf("\n    AD   -        \xAD");
printf("\n    AE   -        \xAE");
printf("\n    AF   -        \xAF");
printf("\n    AG   -        \xAG");
printf("\n    AH   -        \xAH");
printf("\n    AI   -        \xAI");
printf("\n    AJ   -        \xAJ");
printf("\n    AK   -        \xAK");
printf("\n    AL   -        \xAL");
printf("\n    AM   -        \xAM");
printf("\n    AN   -        \xAN");
printf("\n    AO   -        \xAO");
printf("\n    AP   -        \xAP");
printf("\n    AQ   -        \xAQ");
printf("\n    AR   -        \xAR");
printf("\n    AS   -        \xAS");
printf("\n    AT   -        \xAT");
printf("\n    AU   -        \xAU");
printf("\n    AV   -        \xAV");
printf("\n    AW   -        \xAW");
printf("\n    AX   -        \xAX");
printf("\n    AY   -        \xAY");
printf("\n    AZ   -        \xAZ");
printf("\n    B0   -        \xB0");
printf("\n    B1   -        \xB1");
printf("\n    B2   -        \xB2");
printf("\n    B3   -        \xB3");
printf("\n    B4   -        \xB4");
printf("\n    B5   -        \xB5");
printf("\n    B6   -        \xB6");
printf("\n    B7   -        \xB7");
printf("\n    B8   -        \xB8");
printf("\n    B9   -        \xB9");
printf("\n    BA   -        \xBA");
printf("\n    BB   -        \xBB");
printf("\n    BC   -        \xBC");
printf("\n    BD   -        \xBD");
printf("\n    BE   -        \xBE");
printf("\n    BF   -        \xBF");
printf("\n    BG   -        \xBG");
printf("\n    BH   -        \xBH");
printf("\n    BI   -        \xBI");
printf("\n    BJ   -        \xBJ");
printf("\n    BK   -        \xBK");
printf("\n    BL   -        \xBL");
printf("\n    BM   -        \xBM");
printf("\n    BN   -        \xBN");
printf("\n    BO   -        \xBO");
printf("\n    BP   -        \xBP");
printf("\n    BQ   -        \xBQ");
printf("\n    BR   -        \xBR");
printf("\n    BS   -        \xBS");
printf("\n    BT   -        \xBT");
printf("\n    BU   -        \xBU");
printf("\n    BV   -        \xBV");
printf("\n    BW   -        \xBW");
printf("\n    BX   -        \xBX");
printf("\n    BY   -        \xBY");
printf("\n    BZ   -        \xBZ");
printf("\n    C0   -        \xC0");
printf("\n    C1   -        \xC1");
printf("\n    C2   -        \xC2");
printf("\n    C3   -        \xC3");
printf("\n    C4   -        \xC4");
printf("\n    C5   -        \xC5");
printf("\n    C6   -        \xC6");
printf("\n    C7   -        \xC7");
printf("\n    C8   -        \xC8");
printf("\n    C9   -        \xC9");
printf("\n    CA   -        \xCA");
printf("\n    CB   -        \xCB");
printf("\n    CC   -        \xCC");
printf("\n    CD   -        \xCD");
printf("\n    CE   -        \xCE");
printf("\n    CF   -        \xCF");
printf("\n    CG   -        \xCG");
printf("\n    CH   -        \xCH");
printf("\n    CI   -        \xCI");
printf("\n    CJ   -        \xCJ");
printf("\n    CK   -        \xCK");
printf("\n    CL   -        \xCL");
printf("\n    CM   -        \xCM");
printf("\n    CN   -        \xCN");
printf("\n    CO   -        \xCO");
printf("\n    CP   -        \xCP");
printf("\n    CQ   -        \xCQ");
printf("\n    CR   -        \xCR");
printf("\n    CS   -        \xCS");
printf("\n    CT   -        \xCT");
printf("\n    CU   -        \xCU");
printf("\n    CV   -        \xCV");
printf("\n    CW   -        \xCW");
printf("\n    CX   -        \xCX");
printf("\n    CY   -        \xCY");
printf("\n    CZ   -        \xCZ");
printf("\n    D0   -        \xD0");
printf("\n    D1   -        \xD1");
printf("\n    D2   -        \xD2");
printf("\n    D3   -        \xD3");
printf("\n    D4   -        \xD4");
printf("\n    D5   -        \xD5");
printf("\n    D6   -        \xD6");
printf("\n    D7   -        \xD7");
printf("\n    D8   -        \xD8");
printf("\n    D9   -        \xD9");
printf("\n    DA   -        \xDA");
printf("\n    DB   -        \xDB");
printf("\n    DC   -        \xDC");
printf("\n    DD   -        \xDD");
printf("\n    DE   -        \xDE");
printf("\n    DF   -        \xDF");
printf("\n    DG   -        \xDG");
printf("\n    DH   -        \xDH");
printf("\n    DI   -        \xDI");
printf("\n    DJ   -        \xDJ");
printf("\n    DK   -        \xDK");
printf("\n    DL   -        \xDL");
printf("\n    DM   -        \xDM");
printf("\n    DN   -        \xDN");
printf("\n    DO   -        \xDO");
printf("\n    DP   -        \xDP");
printf("\n    DQ   -        \xDQ");
printf("\n    DR   -        \xDR");
printf("\n    DS   -        \xDS");
printf("\n    DT   -        \xDT");
printf("\n    DU   -        \xDU");
printf("\n    DV   -        \xDV");
printf("\n    DW   -        \xDW");
printf("\n    DX   -        \xDX");
printf("\n    DY   -        \xDY");
printf("\n    DZ   -        \xDZ");



	printf("\n");
	printf("1  -  %c \n",1);
printf("2  -  %c \n",2);
printf("3  -  %c \n",3);
printf("4  -  %c \n",4);
printf("5  -  %c \n",5);
printf("6  -  %c \n",6);
printf("7  -  %c \n",7);
printf("8  -  %c \n",8);
printf("9  -  %c \n",9);
printf("10  -  %c \n",10);
printf("11  -  %c \n",11);
printf("12  -  %c \n",12);
printf("13  -  %c \n",13);
printf("14  -  %c \n",14);
printf("15  -  %c \n",15);
printf("16  -  %c \n",16);
printf("17  -  %c \n",17);
printf("18  -  %c \n",18);
printf("19  -  %c \n",19);
printf("20  -  %c \n",20);
printf("21  -  %c \n",21);
printf("22  -  %c \n",22);
printf("23  -  %c \n",23);
printf("24  -  %c \n",24);
printf("25  -  %c \n",25);
printf("26  -  %c \n",26);
printf("27  -  %c \n",27);
printf("28  -  %c \n",28);
printf("29  -  %c \n",29);
printf("30  -  %c \n",30);
printf("31  -  %c \n",31);
printf("32  -  %c \n",32);
printf("33  -  %c \n",33);
printf("34  -  %c \n",34);
printf("35  -  %c \n",35);
printf("36  -  %c \n",36);
printf("37  -  %c \n",37);
printf("38  -  %c \n",38);
printf("39  -  %c \n",39);
printf("40  -  %c \n",40);
printf("41  -  %c \n",41);
printf("42  -  %c \n",42);
printf("43  -  %c \n",43);
printf("44  -  %c \n",44);
printf("45  -  %c \n",45);
printf("46  -  %c \n",46);
printf("47  -  %c \n",47);
printf("48  -  %c \n",48);
printf("49  -  %c \n",49);
printf("50  -  %c \n",50);
printf("51  -  %c \n",51);
printf("52  -  %c \n",52);
printf("53  -  %c \n",53);
printf("54  -  %c \n",54);
printf("55  -  %c \n",55);
printf("56  -  %c \n",56);
printf("57  -  %c \n",57);
printf("58  -  %c \n",58);
printf("59  -  %c \n",59);
printf("60  -  %c \n",60);
printf("61  -  %c \n",61);
printf("62  -  %c \n",62);
printf("63  -  %c \n",63);
printf("64  -  %c \n",64);
printf("65  -  %c \n",65);
printf("66  -  %c \n",66);
printf("67  -  %c \n",67);
printf("68  -  %c \n",68);
printf("69  -  %c \n",69);
printf("70  -  %c \n",70);
printf("71  -  %c \n",71);
printf("72  -  %c \n",72);
printf("73  -  %c \n",73);
printf("74  -  %c \n",74);
printf("75  -  %c \n",75);
printf("76  -  %c \n",76);
printf("77  -  %c \n",77);
printf("78  -  %c \n",78);
printf("79  -  %c \n",79);
printf("80  -  %c \n",80);
printf("81  -  %c \n",81);
printf("82  -  %c \n",82);
printf("83  -  %c \n",83);
printf("84  -  %c \n",84);
printf("85  -  %c \n",85);
printf("86  -  %c \n",86);
printf("87  -  %c \n",87);
printf("88  -  %c \n",88);
printf("89  -  %c \n",89);
printf("90  -  %c \n",90);
printf("91  -  %c \n",91);
printf("92  -  %c \n",92);
printf("93  -  %c \n",93);
printf("94  -  %c \n",94);
printf("95  -  %c \n",95);
printf("96  -  %c \n",96);
printf("97  -  %c \n",97);
printf("98  -  %c \n",98);
printf("99  -  %c \n",99);
printf("100  -  %c \n",100);
printf("101  -  %c \n",101);
printf("102  -  %c \n",102);
printf("103  -  %c \n",103);
printf("104  -  %c \n",104);
printf("105  -  %c \n",105);
printf("106  -  %c \n",106);
printf("107  -  %c \n",107);
printf("108  -  %c \n",108);
printf("109  -  %c \n",109);
printf("110  -  %c \n",110);
printf("111  -  %c \n",111);
printf("112  -  %c \n",112);
printf("113  -  %c \n",113);
printf("114  -  %c \n",114);
printf("115  -  %c \n",115);
printf("116  -  %c \n",116);
printf("117  -  %c \n",117);
printf("118  -  %c \n",118);
printf("119  -  %c \n",119);
printf("120  -  %c \n",120);
printf("121  -  %c \n",121);
printf("122  -  %c \n",122);
printf("123  -  %c \n",123);
printf("124  -  %c \n",124);
printf("125  -  %c \n",125);
printf("126  -  %c \n",126);
printf("127  -  %c \n",127);
printf("128  -  %c \n",128);
printf("129  -  %c \n",129);
printf("130  -  %c \n",130);
printf("131  -  %c \n",131);
printf("132  -  %c \n",132);
printf("133  -  %c \n",133);
printf("134  -  %c \n",134);
printf("135  -  %c \n",135);
printf("136  -  %c \n",136);
printf("137  -  %c \n",137);
printf("138  -  %c \n",138);
printf("139  -  %c \n",139);
printf("140  -  %c \n",140);
printf("141  -  %c \n",141);
printf("142  -  %c \n",142);
printf("143  -  %c \n",143);
printf("144  -  %c \n",144);
printf("145  -  %c \n",145);
printf("146  -  %c \n",146);
printf("147  -  %c \n",147);
printf("148  -  %c \n",148);
printf("149  -  %c \n",149);
printf("150  -  %c \n",150);
printf("151  -  %c \n",151);
printf("152  -  %c \n",152);
printf("153  -  %c \n",153);
printf("154  -  %c \n",154);
printf("155  -  %c \n",155);
printf("156  -  %c \n",156);
printf("157  -  %c \n",157);
printf("158  -  %c \n",158);
printf("159  -  %c \n",159);
printf("160  -  %c \n",160);
printf("161  -  %c \n",161);
printf("162  -  %c \n",162);
printf("163  -  %c \n",163);
printf("164  -  %c \n",164);
printf("165  -  %c \n",165);
printf("166  -  %c \n",166);
printf("167  -  %c \n",167);
printf("168  -  %c \n",168);
printf("169  -  %c \n",169);
printf("170  -  %c \n",170);
printf("171  -  %c \n",171);
printf("172  -  %c \n",172);
printf("173  -  %c \n",173);
printf("174  -  %c \n",174);
printf("175  -  %c \n",175);
printf("176  -  %c \n",176);
printf("177  -  %c \n",177);
printf("178  -  %c \n",178);
printf("179  -  %c \n",179);
printf("180  -  %c \n",180);
printf("181  -  %c \n",181);
printf("182  -  %c \n",182);
printf("183  -  %c \n",183);
printf("184  -  %c \n",184);
printf("185  -  %c \n",185);
printf("186  -  %c \n",186);
printf("187  -  %c \n",187);
printf("188  -  %c \n",188);
printf("189  -  %c \n",189);
printf("190  -  %c \n",190);
printf("191  -  %c \n",191);
printf("192  -  %c \n",192);
printf("193  -  %c \n",193);
printf("194  -  %c \n",194);
printf("195  -  %c \n",195);
printf("196  -  %c \n",196);
printf("197  -  %c \n",197);
printf("198  -  %c \n",198);
printf("199  -  %c \n",199);
printf("200  -  %c \n",200);
printf("201  -  %c \n",201);
printf("202  -  %c \n",202);
printf("203  -  %c \n",203);
printf("204  -  %c \n",204);
printf("205  -  %c \n",205);
printf("206  -  %c \n",206);
printf("207  -  %c \n",207);
printf("208  -  %c \n",208);
printf("209  -  %c \n",209);
printf("210  -  %c \n",210);
printf("211  -  %c \n",211);
printf("212  -  %c \n",212);
printf("213  -  %c \n",213);
printf("214  -  %c \n",214);
printf("215  -  %c \n",215);
printf("216  -  %c \n",216);
printf("217  -  %c \n",217);
printf("218  -  %c \n",218);
printf("219  -  %c \n",219);
printf("220  -  %c \n",220);
printf("221  -  %c \n",221);
printf("222  -  %c \n",222);
printf("223  -  %c \n",223);
printf("224  -  %c \n",224);
printf("225  -  %c \n",225);
printf("226  -  %c \n",226);
printf("227  -  %c \n",227);
printf("228  -  %c \n",228);
printf("229  -  %c \n",229);
printf("230  -  %c \n",230);
printf("231  -  %c \n",231);
printf("232  -  %c \n",232);
printf("233  -  %c \n",233);
printf("234  -  %c \n",234);
printf("235  -  %c \n",235);
printf("236  -  %c \n",236);
printf("237  -  %c \n",237);
printf("238  -  %c \n",238);
printf("239  -  %c \n",239);
printf("240  -  %c \n",240);
printf("241  -  %c \n",241);
printf("242  -  %c \n",242);
printf("243  -  %c \n",243);
printf("244  -  %c \n",244);
printf("245  -  %c \n",245);
printf("246  -  %c \n",246);
printf("247  -  %c \n",247);
printf("248  -  %c \n",248);
printf("249  -  %c \n",249);
printf("250  -  %c \n",250);
printf("251  -  %c \n",251);
printf("252  -  %c \n",252);
printf("253  -  %c \n",253);
printf("254  -  %c \n",254);
printf("255  -  %c \n",255);
printf("256  -  %c \n",256);


	printf("\n");
	/*for (i = 1; i <= 100; i++)
	{
		printf("\xDB");
		Sleep(100);

	}
	printf("\n");
	int j;
	int espacosAntes = 45;
	for (j = 1; j <= 100; j++)
	{
		printf("\r%*d %%", espacosAntes, j);
		fflush(stdout);
		Sleep(100);
	}*/

}


int main()
{
	system("color F0");
	BarraProgressao();
	printf("\n");
	return 0;
}


